// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.1
// 	protoc        v5.29.2
// source: services/task_service.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskServiceSubscribeCode int32

const (
	TaskServiceSubscribeCode_CANCEL TaskServiceSubscribeCode = 0
)

// Enum value maps for TaskServiceSubscribeCode.
var (
	TaskServiceSubscribeCode_name = map[int32]string{
		0: "CANCEL",
	}
	TaskServiceSubscribeCode_value = map[string]int32{
		"CANCEL": 0,
	}
)

func (x TaskServiceSubscribeCode) Enum() *TaskServiceSubscribeCode {
	p := new(TaskServiceSubscribeCode)
	*p = x
	return p
}

func (x TaskServiceSubscribeCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskServiceSubscribeCode) Descriptor() protoreflect.EnumDescriptor {
	return file_services_task_service_proto_enumTypes[0].Descriptor()
}

func (TaskServiceSubscribeCode) Type() protoreflect.EnumType {
	return &file_services_task_service_proto_enumTypes[0]
}

func (x TaskServiceSubscribeCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskServiceSubscribeCode.Descriptor instead.
func (TaskServiceSubscribeCode) EnumDescriptor() ([]byte, []int) {
	return file_services_task_service_proto_rawDescGZIP(), []int{0}
}

type TaskServiceConnectCode int32

const (
	TaskServiceConnectCode_INSERT_DATA TaskServiceConnectCode = 0
	TaskServiceConnectCode_INSERT_LOGS TaskServiceConnectCode = 1
	TaskServiceConnectCode_PING        TaskServiceConnectCode = 2
)

// Enum value maps for TaskServiceConnectCode.
var (
	TaskServiceConnectCode_name = map[int32]string{
		0: "INSERT_DATA",
		1: "INSERT_LOGS",
		2: "PING",
	}
	TaskServiceConnectCode_value = map[string]int32{
		"INSERT_DATA": 0,
		"INSERT_LOGS": 1,
		"PING":        2,
	}
)

func (x TaskServiceConnectCode) Enum() *TaskServiceConnectCode {
	p := new(TaskServiceConnectCode)
	*p = x
	return p
}

func (x TaskServiceConnectCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskServiceConnectCode) Descriptor() protoreflect.EnumDescriptor {
	return file_services_task_service_proto_enumTypes[1].Descriptor()
}

func (TaskServiceConnectCode) Type() protoreflect.EnumType {
	return &file_services_task_service_proto_enumTypes[1]
}

func (x TaskServiceConnectCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskServiceConnectCode.Descriptor instead.
func (TaskServiceConnectCode) EnumDescriptor() ([]byte, []int) {
	return file_services_task_service_proto_rawDescGZIP(), []int{1}
}

type TaskServiceConnectResponseCode int32

const (
	TaskServiceConnectResponseCode_CONNECT_SUCCESS         TaskServiceConnectResponseCode = 0
	TaskServiceConnectResponseCode_CONNECT_ERROR           TaskServiceConnectResponseCode = 1
	TaskServiceConnectResponseCode_CONNECT_INVALID_REQUEST TaskServiceConnectResponseCode = 2
	TaskServiceConnectResponseCode_CONNECT_TASK_NOT_FOUND  TaskServiceConnectResponseCode = 3
)

// Enum value maps for TaskServiceConnectResponseCode.
var (
	TaskServiceConnectResponseCode_name = map[int32]string{
		0: "CONNECT_SUCCESS",
		1: "CONNECT_ERROR",
		2: "CONNECT_INVALID_REQUEST",
		3: "CONNECT_TASK_NOT_FOUND",
	}
	TaskServiceConnectResponseCode_value = map[string]int32{
		"CONNECT_SUCCESS":         0,
		"CONNECT_ERROR":           1,
		"CONNECT_INVALID_REQUEST": 2,
		"CONNECT_TASK_NOT_FOUND":  3,
	}
)

func (x TaskServiceConnectResponseCode) Enum() *TaskServiceConnectResponseCode {
	p := new(TaskServiceConnectResponseCode)
	*p = x
	return p
}

func (x TaskServiceConnectResponseCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskServiceConnectResponseCode) Descriptor() protoreflect.EnumDescriptor {
	return file_services_task_service_proto_enumTypes[2].Descriptor()
}

func (TaskServiceConnectResponseCode) Type() protoreflect.EnumType {
	return &file_services_task_service_proto_enumTypes[2]
}

func (x TaskServiceConnectResponseCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskServiceConnectResponseCode.Descriptor instead.
func (TaskServiceConnectResponseCode) EnumDescriptor() ([]byte, []int) {
	return file_services_task_service_proto_rawDescGZIP(), []int{2}
}

type TaskServiceSendNotificationResponseCode int32

const (
	TaskServiceSendNotificationResponseCode_NOTIFICATION_SUCCESS  TaskServiceSendNotificationResponseCode = 0
	TaskServiceSendNotificationResponseCode_NOTIFICATION_ERROR    TaskServiceSendNotificationResponseCode = 1
	TaskServiceSendNotificationResponseCode_NOTIFICATION_DISABLED TaskServiceSendNotificationResponseCode = 2
)

// Enum value maps for TaskServiceSendNotificationResponseCode.
var (
	TaskServiceSendNotificationResponseCode_name = map[int32]string{
		0: "NOTIFICATION_SUCCESS",
		1: "NOTIFICATION_ERROR",
		2: "NOTIFICATION_DISABLED",
	}
	TaskServiceSendNotificationResponseCode_value = map[string]int32{
		"NOTIFICATION_SUCCESS":  0,
		"NOTIFICATION_ERROR":    1,
		"NOTIFICATION_DISABLED": 2,
	}
)

func (x TaskServiceSendNotificationResponseCode) Enum() *TaskServiceSendNotificationResponseCode {
	p := new(TaskServiceSendNotificationResponseCode)
	*p = x
	return p
}

func (x TaskServiceSendNotificationResponseCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskServiceSendNotificationResponseCode) Descriptor() protoreflect.EnumDescriptor {
	return file_services_task_service_proto_enumTypes[3].Descriptor()
}

func (TaskServiceSendNotificationResponseCode) Type() protoreflect.EnumType {
	return &file_services_task_service_proto_enumTypes[3]
}

func (x TaskServiceSendNotificationResponseCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskServiceSendNotificationResponseCode.Descriptor instead.
func (TaskServiceSendNotificationResponseCode) EnumDescriptor() ([]byte, []int) {
	return file_services_task_service_proto_rawDescGZIP(), []int{3}
}

type ProcessStatus int32

const (
	ProcessStatus_PROCESS_UNKNOWN   ProcessStatus = 0
	ProcessStatus_PROCESS_RUNNING   ProcessStatus = 1
	ProcessStatus_PROCESS_FINISHED  ProcessStatus = 2
	ProcessStatus_PROCESS_ERROR     ProcessStatus = 3
	ProcessStatus_PROCESS_NOT_FOUND ProcessStatus = 4
	ProcessStatus_PROCESS_ZOMBIE    ProcessStatus = 5
)

// Enum value maps for ProcessStatus.
var (
	ProcessStatus_name = map[int32]string{
		0: "PROCESS_UNKNOWN",
		1: "PROCESS_RUNNING",
		2: "PROCESS_FINISHED",
		3: "PROCESS_ERROR",
		4: "PROCESS_NOT_FOUND",
		5: "PROCESS_ZOMBIE",
	}
	ProcessStatus_value = map[string]int32{
		"PROCESS_UNKNOWN":   0,
		"PROCESS_RUNNING":   1,
		"PROCESS_FINISHED":  2,
		"PROCESS_ERROR":     3,
		"PROCESS_NOT_FOUND": 4,
		"PROCESS_ZOMBIE":    5,
	}
)

func (x ProcessStatus) Enum() *ProcessStatus {
	p := new(ProcessStatus)
	*p = x
	return p
}

func (x ProcessStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProcessStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_services_task_service_proto_enumTypes[4].Descriptor()
}

func (ProcessStatus) Type() protoreflect.EnumType {
	return &file_services_task_service_proto_enumTypes[4]
}

func (x ProcessStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProcessStatus.Descriptor instead.
func (ProcessStatus) EnumDescriptor() ([]byte, []int) {
	return file_services_task_service_proto_rawDescGZIP(), []int{4}
}

type TaskServiceSubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskServiceSubscribeRequest) Reset() {
	*x = TaskServiceSubscribeRequest{}
	mi := &file_services_task_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskServiceSubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskServiceSubscribeRequest) ProtoMessage() {}

func (x *TaskServiceSubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_task_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskServiceSubscribeRequest.ProtoReflect.Descriptor instead.
func (*TaskServiceSubscribeRequest) Descriptor() ([]byte, []int) {
	return file_services_task_service_proto_rawDescGZIP(), []int{0}
}

func (x *TaskServiceSubscribeRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type TaskServiceSubscribeResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Code          TaskServiceSubscribeCode `protobuf:"varint,1,opt,name=code,proto3,enum=grpc.TaskServiceSubscribeCode" json:"code,omitempty"`
	TaskId        string                   `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Force         bool                     `protobuf:"varint,3,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskServiceSubscribeResponse) Reset() {
	*x = TaskServiceSubscribeResponse{}
	mi := &file_services_task_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskServiceSubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskServiceSubscribeResponse) ProtoMessage() {}

func (x *TaskServiceSubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_task_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskServiceSubscribeResponse.ProtoReflect.Descriptor instead.
func (*TaskServiceSubscribeResponse) Descriptor() ([]byte, []int) {
	return file_services_task_service_proto_rawDescGZIP(), []int{1}
}

func (x *TaskServiceSubscribeResponse) GetCode() TaskServiceSubscribeCode {
	if x != nil {
		return x.Code
	}
	return TaskServiceSubscribeCode_CANCEL
}

func (x *TaskServiceSubscribeResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskServiceSubscribeResponse) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type TaskServiceConnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          TaskServiceConnectCode `protobuf:"varint,1,opt,name=code,proto3,enum=grpc.TaskServiceConnectCode" json:"code,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskServiceConnectRequest) Reset() {
	*x = TaskServiceConnectRequest{}
	mi := &file_services_task_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskServiceConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskServiceConnectRequest) ProtoMessage() {}

func (x *TaskServiceConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_task_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskServiceConnectRequest.ProtoReflect.Descriptor instead.
func (*TaskServiceConnectRequest) Descriptor() ([]byte, []int) {
	return file_services_task_service_proto_rawDescGZIP(), []int{2}
}

func (x *TaskServiceConnectRequest) GetCode() TaskServiceConnectCode {
	if x != nil {
		return x.Code
	}
	return TaskServiceConnectCode_INSERT_DATA
}

func (x *TaskServiceConnectRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskServiceConnectRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type TaskServiceConnectResponse struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Code          TaskServiceConnectResponseCode `protobuf:"varint,1,opt,name=code,proto3,enum=grpc.TaskServiceConnectResponseCode" json:"code,omitempty"`
	Message       string                         `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Error         string                         `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskServiceConnectResponse) Reset() {
	*x = TaskServiceConnectResponse{}
	mi := &file_services_task_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskServiceConnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskServiceConnectResponse) ProtoMessage() {}

func (x *TaskServiceConnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_task_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskServiceConnectResponse.ProtoReflect.Descriptor instead.
func (*TaskServiceConnectResponse) Descriptor() ([]byte, []int) {
	return file_services_task_service_proto_rawDescGZIP(), []int{3}
}

func (x *TaskServiceConnectResponse) GetCode() TaskServiceConnectResponseCode {
	if x != nil {
		return x.Code
	}
	return TaskServiceConnectResponseCode_CONNECT_SUCCESS
}

func (x *TaskServiceConnectResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TaskServiceConnectResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type TaskServiceFetchTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeKey       string                 `protobuf:"bytes,1,opt,name=node_key,json=nodeKey,proto3" json:"node_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskServiceFetchTaskRequest) Reset() {
	*x = TaskServiceFetchTaskRequest{}
	mi := &file_services_task_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskServiceFetchTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskServiceFetchTaskRequest) ProtoMessage() {}

func (x *TaskServiceFetchTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_task_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskServiceFetchTaskRequest.ProtoReflect.Descriptor instead.
func (*TaskServiceFetchTaskRequest) Descriptor() ([]byte, []int) {
	return file_services_task_service_proto_rawDescGZIP(), []int{4}
}

func (x *TaskServiceFetchTaskRequest) GetNodeKey() string {
	if x != nil {
		return x.NodeKey
	}
	return ""
}

type TaskServiceFetchTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskServiceFetchTaskResponse) Reset() {
	*x = TaskServiceFetchTaskResponse{}
	mi := &file_services_task_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskServiceFetchTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskServiceFetchTaskResponse) ProtoMessage() {}

func (x *TaskServiceFetchTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_task_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskServiceFetchTaskResponse.ProtoReflect.Descriptor instead.
func (*TaskServiceFetchTaskResponse) Descriptor() ([]byte, []int) {
	return file_services_task_service_proto_rawDescGZIP(), []int{5}
}

func (x *TaskServiceFetchTaskResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type TaskServiceSendNotificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeKey       string                 `protobuf:"bytes,1,opt,name=node_key,json=nodeKey,proto3" json:"node_key,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskServiceSendNotificationRequest) Reset() {
	*x = TaskServiceSendNotificationRequest{}
	mi := &file_services_task_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskServiceSendNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskServiceSendNotificationRequest) ProtoMessage() {}

func (x *TaskServiceSendNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_task_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskServiceSendNotificationRequest.ProtoReflect.Descriptor instead.
func (*TaskServiceSendNotificationRequest) Descriptor() ([]byte, []int) {
	return file_services_task_service_proto_rawDescGZIP(), []int{6}
}

func (x *TaskServiceSendNotificationRequest) GetNodeKey() string {
	if x != nil {
		return x.NodeKey
	}
	return ""
}

func (x *TaskServiceSendNotificationRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type TaskServiceSendNotificationResponse struct {
	state         protoimpl.MessageState                  `protogen:"open.v1"`
	Code          TaskServiceSendNotificationResponseCode `protobuf:"varint,1,opt,name=code,proto3,enum=grpc.TaskServiceSendNotificationResponseCode" json:"code,omitempty"`
	Message       string                                  `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Error         string                                  `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskServiceSendNotificationResponse) Reset() {
	*x = TaskServiceSendNotificationResponse{}
	mi := &file_services_task_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskServiceSendNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskServiceSendNotificationResponse) ProtoMessage() {}

func (x *TaskServiceSendNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_task_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskServiceSendNotificationResponse.ProtoReflect.Descriptor instead.
func (*TaskServiceSendNotificationResponse) Descriptor() ([]byte, []int) {
	return file_services_task_service_proto_rawDescGZIP(), []int{7}
}

func (x *TaskServiceSendNotificationResponse) GetCode() TaskServiceSendNotificationResponseCode {
	if x != nil {
		return x.Code
	}
	return TaskServiceSendNotificationResponseCode_NOTIFICATION_SUCCESS
}

func (x *TaskServiceSendNotificationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TaskServiceSendNotificationResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type TaskServiceCheckProcessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Pid           int32                  `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskServiceCheckProcessRequest) Reset() {
	*x = TaskServiceCheckProcessRequest{}
	mi := &file_services_task_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskServiceCheckProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskServiceCheckProcessRequest) ProtoMessage() {}

func (x *TaskServiceCheckProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_task_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskServiceCheckProcessRequest.ProtoReflect.Descriptor instead.
func (*TaskServiceCheckProcessRequest) Descriptor() ([]byte, []int) {
	return file_services_task_service_proto_rawDescGZIP(), []int{8}
}

func (x *TaskServiceCheckProcessRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskServiceCheckProcessRequest) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

type TaskServiceCheckProcessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Pid           int32                  `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	Status        ProcessStatus          `protobuf:"varint,3,opt,name=status,proto3,enum=grpc.ProcessStatus" json:"status,omitempty"`
	ExitCode      int32                  `protobuf:"varint,4,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskServiceCheckProcessResponse) Reset() {
	*x = TaskServiceCheckProcessResponse{}
	mi := &file_services_task_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskServiceCheckProcessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskServiceCheckProcessResponse) ProtoMessage() {}

func (x *TaskServiceCheckProcessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_task_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskServiceCheckProcessResponse.ProtoReflect.Descriptor instead.
func (*TaskServiceCheckProcessResponse) Descriptor() ([]byte, []int) {
	return file_services_task_service_proto_rawDescGZIP(), []int{9}
}

func (x *TaskServiceCheckProcessResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskServiceCheckProcessResponse) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *TaskServiceCheckProcessResponse) GetStatus() ProcessStatus {
	if x != nil {
		return x.Status
	}
	return ProcessStatus_PROCESS_UNKNOWN
}

func (x *TaskServiceCheckProcessResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *TaskServiceCheckProcessResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_services_task_service_proto protoreflect.FileDescriptor

var file_services_task_service_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x74, 0x61, 0x73, 0x6b, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67,
	0x72, 0x70, 0x63, 0x22, 0x36, 0x0a, 0x1b, 0x54, 0x61, 0x73, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x22, 0x81, 0x01, 0x0a, 0x1c,
	0x54, 0x61, 0x73, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x53, 0x75, 0x62, 0x73, 0x63,
	0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1e, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x53, 0x75, 0x62,
	0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x12, 0x17, 0x0a, 0x07, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x6f, 0x72,
	0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x66, 0x6f, 0x72, 0x63, 0x65, 0x22,
	0x7a, 0x0a, 0x19, 0x54, 0x61, 0x73, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x43, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x30, 0x0a, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x43, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x17,
	0x0a, 0x07, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x86, 0x01, 0x0a, 0x1a,
	0x54, 0x61, 0x73, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x43, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x24, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x54, 0x61, 0x73, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x43, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x22, 0x38, 0x0a, 0x1b, 0x54, 0x61, 0x73, 0x6b, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x46, 0x65, 0x74, 0x63, 0x68, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6e, 0x6f, 0x64, 0x65, 0x4b, 0x65, 0x79, 0x22, 0x37,
	0x0a, 0x1c, 0x54, 0x61, 0x73, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x46, 0x65, 0x74,
	0x63, 0x68, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x17,
	0x0a, 0x07, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x22, 0x58, 0x0a, 0x22, 0x54, 0x61, 0x73, 0x6b, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x53, 0x65, 0x6e, 0x64, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a,
	0x08, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6e, 0x6f, 0x64, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x61, 0x73, 0x6b,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49,
	0x64, 0x22, 0x98, 0x01, 0x0a, 0x23, 0x54, 0x61, 0x73, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x53, 0x65, 0x6e, 0x64, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x41, 0x0a, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2d, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x54,
	0x61, 0x73, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x53, 0x65, 0x6e, 0x64, 0x4e, 0x6f,
	0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x4b, 0x0a, 0x1e,
	0x54, 0x61, 0x73, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x43, 0x68, 0x65, 0x63, 0x6b,
	0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17,
	0x0a, 0x07, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x70, 0x69, 0x64, 0x22, 0xbb, 0x01, 0x0a, 0x1f, 0x54, 0x61,
	0x73, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x50, 0x72,
	0x6f, 0x63, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x17, 0x0a,
	0x07, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x03, 0x70, 0x69, 0x64, 0x12, 0x2b, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x65, 0x78, 0x69, 0x74, 0x5f, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x65, 0x78, 0x69, 0x74, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2a, 0x26, 0x0a, 0x18, 0x54, 0x61, 0x73, 0x6b, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x43,
	0x6f, 0x64, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x43, 0x41, 0x4e, 0x43, 0x45, 0x4c, 0x10, 0x00, 0x2a,
	0x44, 0x0a, 0x16, 0x54, 0x61, 0x73, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x43, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x0f, 0x0a, 0x0b, 0x49, 0x4e, 0x53,
	0x45, 0x52, 0x54, 0x5f, 0x44, 0x41, 0x54, 0x41, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x49, 0x4e,
	0x53, 0x45, 0x52, 0x54, 0x5f, 0x4c, 0x4f, 0x47, 0x53, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x50,
	0x49, 0x4e, 0x47, 0x10, 0x02, 0x2a, 0x81, 0x01, 0x0a, 0x1e, 0x54, 0x61, 0x73, 0x6b, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x13, 0x0a, 0x0f, 0x43, 0x4f, 0x4e, 0x4e,
	0x45, 0x43, 0x54, 0x5f, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x00, 0x12, 0x11, 0x0a,
	0x0d, 0x43, 0x4f, 0x4e, 0x4e, 0x45, 0x43, 0x54, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x01,
	0x12, 0x1b, 0x0a, 0x17, 0x43, 0x4f, 0x4e, 0x4e, 0x45, 0x43, 0x54, 0x5f, 0x49, 0x4e, 0x56, 0x41,
	0x4c, 0x49, 0x44, 0x5f, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54, 0x10, 0x02, 0x12, 0x1a, 0x0a,
	0x16, 0x43, 0x4f, 0x4e, 0x4e, 0x45, 0x43, 0x54, 0x5f, 0x54, 0x41, 0x53, 0x4b, 0x5f, 0x4e, 0x4f,
	0x54, 0x5f, 0x46, 0x4f, 0x55, 0x4e, 0x44, 0x10, 0x03, 0x2a, 0x76, 0x0a, 0x27, 0x54, 0x61, 0x73,
	0x6b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x53, 0x65, 0x6e, 0x64, 0x4e, 0x6f, 0x74, 0x69,
	0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x43, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x14, 0x4e, 0x4f, 0x54, 0x49, 0x46, 0x49, 0x43, 0x41,
	0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x00, 0x12, 0x16,
	0x0a, 0x12, 0x4e, 0x4f, 0x54, 0x49, 0x46, 0x49, 0x43, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x45,
	0x52, 0x52, 0x4f, 0x52, 0x10, 0x01, 0x12, 0x19, 0x0a, 0x15, 0x4e, 0x4f, 0x54, 0x49, 0x46, 0x49,
	0x43, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x44, 0x49, 0x53, 0x41, 0x42, 0x4c, 0x45, 0x44, 0x10,
	0x02, 0x2a, 0x8d, 0x01, 0x0a, 0x0d, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x13, 0x0a, 0x0f, 0x50, 0x52, 0x4f, 0x43, 0x45, 0x53, 0x53, 0x5f, 0x55,
	0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f, 0x50, 0x52, 0x4f, 0x43,
	0x45, 0x53, 0x53, 0x5f, 0x52, 0x55, 0x4e, 0x4e, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x14, 0x0a,
	0x10, 0x50, 0x52, 0x4f, 0x43, 0x45, 0x53, 0x53, 0x5f, 0x46, 0x49, 0x4e, 0x49, 0x53, 0x48, 0x45,
	0x44, 0x10, 0x02, 0x12, 0x11, 0x0a, 0x0d, 0x50, 0x52, 0x4f, 0x43, 0x45, 0x53, 0x53, 0x5f, 0x45,
	0x52, 0x52, 0x4f, 0x52, 0x10, 0x03, 0x12, 0x15, 0x0a, 0x11, 0x50, 0x52, 0x4f, 0x43, 0x45, 0x53,
	0x53, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x46, 0x4f, 0x55, 0x4e, 0x44, 0x10, 0x04, 0x12, 0x12, 0x0a,
	0x0e, 0x50, 0x52, 0x4f, 0x43, 0x45, 0x53, 0x53, 0x5f, 0x5a, 0x4f, 0x4d, 0x42, 0x49, 0x45, 0x10,
	0x05, 0x32, 0xd9, 0x03, 0x0a, 0x0b, 0x54, 0x61, 0x73, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x56, 0x0a, 0x09, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x12, 0x21,
	0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x22, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x12, 0x52, 0x0a, 0x07, 0x43, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x12, 0x1f, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x54, 0x61, 0x73, 0x6b,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x54, 0x61, 0x73,
	0x6b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x12, 0x54, 0x0a,
	0x09, 0x46, 0x65, 0x74, 0x63, 0x68, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x21, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x46, 0x65, 0x74,
	0x63, 0x68, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x46, 0x65, 0x74, 0x63, 0x68, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x69, 0x0a, 0x10, 0x53, 0x65, 0x6e, 0x64, 0x4e, 0x6f, 0x74, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x28, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x54,
	0x61, 0x73, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x53, 0x65, 0x6e, 0x64, 0x4e, 0x6f,
	0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x29, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x53, 0x65, 0x6e, 0x64, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5d,
	0x0a, 0x0c, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x12, 0x24,
	0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x54, 0x61, 0x73, 0x6b,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x50, 0x72, 0x6f, 0x63,
	0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x08, 0x5a,
	0x06, 0x2e, 0x3b, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_services_task_service_proto_rawDescOnce sync.Once
	file_services_task_service_proto_rawDescData = file_services_task_service_proto_rawDesc
)

func file_services_task_service_proto_rawDescGZIP() []byte {
	file_services_task_service_proto_rawDescOnce.Do(func() {
		file_services_task_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_services_task_service_proto_rawDescData)
	})
	return file_services_task_service_proto_rawDescData
}

var file_services_task_service_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_services_task_service_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_services_task_service_proto_goTypes = []any{
	(TaskServiceSubscribeCode)(0),                // 0: grpc.TaskServiceSubscribeCode
	(TaskServiceConnectCode)(0),                  // 1: grpc.TaskServiceConnectCode
	(TaskServiceConnectResponseCode)(0),          // 2: grpc.TaskServiceConnectResponseCode
	(TaskServiceSendNotificationResponseCode)(0), // 3: grpc.TaskServiceSendNotificationResponseCode
	(ProcessStatus)(0),                           // 4: grpc.ProcessStatus
	(*TaskServiceSubscribeRequest)(nil),          // 5: grpc.TaskServiceSubscribeRequest
	(*TaskServiceSubscribeResponse)(nil),         // 6: grpc.TaskServiceSubscribeResponse
	(*TaskServiceConnectRequest)(nil),            // 7: grpc.TaskServiceConnectRequest
	(*TaskServiceConnectResponse)(nil),           // 8: grpc.TaskServiceConnectResponse
	(*TaskServiceFetchTaskRequest)(nil),          // 9: grpc.TaskServiceFetchTaskRequest
	(*TaskServiceFetchTaskResponse)(nil),         // 10: grpc.TaskServiceFetchTaskResponse
	(*TaskServiceSendNotificationRequest)(nil),   // 11: grpc.TaskServiceSendNotificationRequest
	(*TaskServiceSendNotificationResponse)(nil),  // 12: grpc.TaskServiceSendNotificationResponse
	(*TaskServiceCheckProcessRequest)(nil),       // 13: grpc.TaskServiceCheckProcessRequest
	(*TaskServiceCheckProcessResponse)(nil),      // 14: grpc.TaskServiceCheckProcessResponse
}
var file_services_task_service_proto_depIdxs = []int32{
	0,  // 0: grpc.TaskServiceSubscribeResponse.code:type_name -> grpc.TaskServiceSubscribeCode
	1,  // 1: grpc.TaskServiceConnectRequest.code:type_name -> grpc.TaskServiceConnectCode
	2,  // 2: grpc.TaskServiceConnectResponse.code:type_name -> grpc.TaskServiceConnectResponseCode
	3,  // 3: grpc.TaskServiceSendNotificationResponse.code:type_name -> grpc.TaskServiceSendNotificationResponseCode
	4,  // 4: grpc.TaskServiceCheckProcessResponse.status:type_name -> grpc.ProcessStatus
	5,  // 5: grpc.TaskService.Subscribe:input_type -> grpc.TaskServiceSubscribeRequest
	7,  // 6: grpc.TaskService.Connect:input_type -> grpc.TaskServiceConnectRequest
	9,  // 7: grpc.TaskService.FetchTask:input_type -> grpc.TaskServiceFetchTaskRequest
	11, // 8: grpc.TaskService.SendNotification:input_type -> grpc.TaskServiceSendNotificationRequest
	13, // 9: grpc.TaskService.CheckProcess:input_type -> grpc.TaskServiceCheckProcessRequest
	6,  // 10: grpc.TaskService.Subscribe:output_type -> grpc.TaskServiceSubscribeResponse
	8,  // 11: grpc.TaskService.Connect:output_type -> grpc.TaskServiceConnectResponse
	10, // 12: grpc.TaskService.FetchTask:output_type -> grpc.TaskServiceFetchTaskResponse
	12, // 13: grpc.TaskService.SendNotification:output_type -> grpc.TaskServiceSendNotificationResponse
	14, // 14: grpc.TaskService.CheckProcess:output_type -> grpc.TaskServiceCheckProcessResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_services_task_service_proto_init() }
func file_services_task_service_proto_init() {
	if File_services_task_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_services_task_service_proto_rawDesc,
			NumEnums:      5,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_task_service_proto_goTypes,
		DependencyIndexes: file_services_task_service_proto_depIdxs,
		EnumInfos:         file_services_task_service_proto_enumTypes,
		MessageInfos:      file_services_task_service_proto_msgTypes,
	}.Build()
	File_services_task_service_proto = out.File
	file_services_task_service_proto_rawDesc = nil
	file_services_task_service_proto_goTypes = nil
	file_services_task_service_proto_depIdxs = nil
}
